
Import('base_env COMPILER')
 
env = base_env.Copy()
COMPILER.SetupSDL(env) 

env.Append(CPPPATH = ['#/source/engine/sdl'], LIBPATH = ['#/source/engine/sdl'], LIBS = ['sdl'])

env.Library('sdl', Split("""
    sdl_network.cpp
    sdl_time.cpp
    sdl_audio.cpp
    sdl_input.cpp
    sdl_screenshot.cpp
    sdl_video.cpp
    sdl_main.cpp
    """))

