import os

Import('base_env BUILD_DIR')

files = [
    'game.sgm',
    'Icons.txt',
    'images/big_particle.png',
    'images/Default.png',
    'images/mouse.png',
    'images/particle.png',
    'images/small_particle.png',
    'images/sphere2.png',
    'scripts/main.js',
    'scripts/Icon.js',
    'scripts/Normal.js',
    'scripts/Particle.js',
    'scripts/ParticleDefine.js',
    'scripts/Quick.js',
    'sounds/intro.mp3',
    'windowstyles/window.rws',
    'windowstyles/swindow.rws']

for f in files:
    base_env.Install(
        os.path.join(os.path.join(BUILD_DIR, 'startup'),
                     os.path.split(f)[0]), f)
