import os

Import('base_env BUILD_DIR')

env = base_env.Copy()
env['BUILDERS']['TextFile'] = Builder(action = 'unix2dos < $SOURCE > $TARGET')

# files that should be converted from unix format to DOS format as part
# of the build
files = ['build-cygwin.txt',
         'build-msvc.txt',
         'changelog.txt',
         'doc_functions.txt',
         'gpl.txt',
         'irc.txt',
         'keys.txt',
         'legal.txt',
         'links.txt',
         'network.txt',
         'optimization.txt',
         'packages.txt',
         'readme.txt',
         'release-howto.txt',
         'Sphere Tutorial.txt',
         'unix.txt']
files += map(lambda n: 'technical/' + n,
             ['coding-style.txt',
              'gameinf.txt',
              'rfn.txt',
              'rmp.txt',
              'rss.txt',
              'rts.txt',
              'rws.txt',
              'spk.txt',
              'videodriver.txt'])
files += map(lambda n: 'system_scripts/' + n,
             ['Clock Info.txt',
              'animation.txt',
              'audio.txt',
              'convert.txt',
              'fademessage.txt',
              'layers.txt',
              'map_animation.txt',
              'menu.txt',
              'timer.txt',
              'wintro.txt'])

# files that should be installed without unix->dos translation
binfiles = []
binfiles += map(lambda n: 'contributed/' + n,
                ['WT_tutorial.rtf',
                 'sphere_doc.pdf'])

for f in files:
    env.TextFile(os.path.join(BUILD_DIR, 'docs', f), f)
for f in binfiles:
    env.InstallAs(os.path.join(BUILD_DIR, 'docs', f), f)

