# @todo build make_new_clut and make_old_clut...  then use them to
# generate the actual table files in source/common


import os

Import('base_env BUILD_DIR COMPILER')

env = base_env.Copy()
COMPILER.SetupSphereCommon(env)
COMPILER.SetupCorona(env)
COMPILER.SetupZLib(env)

utils = ['alphamerge', 'chr2rss', 'image2map', 'image2rss', 'rss2image',
         'setrsstrans', 'tst2rts', 'vmap2rmp', 'vsp2rts']

# spktest is win32 only
if COMPILER.is_win32():
    utils.append('spktest')

for u in utils:
    program = env.Program(os.path.join(u, u), os.path.join(u, u + '.cpp'))
    env.Install(os.path.join(BUILD_DIR, 'util'), program)
