import os

Import('base_env BUILD_DIR COMPILER')

env = base_env.Copy()
COMPILER.SetupSphereCommon(env)
COMPILER.SetupCorona(env)
COMPILER.SetupZLib(env)

utils = ['alphamerge', 'chr2rss', 'image2map', 'image2rss', 'rss2image',
         'setrsstrans', 'spktest', 'tst2rts', 'vmap2rmp', 'vsp2rts']

for u in utils:
    program = env.Program(source = os.path.join(u, u + '.cpp'))
    env.Install(os.path.join(BUILD_DIR, 'util'), program)
