//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by editor.rc
//
#define IDR_MAIN                        101
#define IDD_NEW_PROJECT                 103
#define IDR_TOOLBAR                     106
#define IDI_SDE                         108
#define IDI_PROJECT                     109
#define IDR_MAP                         111
#define IDR_SPRITESET                   113
#define IDR_PROJECT                     114
#define IDI_SOUND                       115
#define IDI_MAP                         117
#define IDI_TILESET                     118
#define IDI_SPRITESET                   119
#define IDI_SCRIPT                      121
#define IDI_IMAGE                       122
#define IDR_PROJECTITEM                 123
#define IDR_SOUND                       124
#define IDR_PROJECTGROUP                125
#define IDI_GAME                        126
#define IDD_GAME_SETTINGS               127
#define IDR_SCRIPT                      129
#define IDR_IMAGE                       131
#define IDD_NUMBER                      132
#define IDD_NEW_MAP                     133
#define IDR_LAYERVIEW                   134
#define IDD_LAYER_PROPERTIES            135
#define IDD_TILE_PROPERTIES             136
#define IDR_ANIMATION                   137
#define IDI_ANIMATION                   138
#define IDR_MAPVIEW                     139
#define IDD_TILESET_SELECTION           140
#define IDB_VOLUMEBAR                   143
#define IDD_MAP_PROPERTIES              144
#define IDR_FONT                        145
#define IDR_WINDOWSTYLE                 146
#define IDD_RESIZE                      148
#define IDD_SPRITE_PROPERTIES           150
#define IDR_SPRITESETVIEW               151
#define IDR_TILESETVIEW                 152
#define IDR_ACCELERATOR                 154
#define IDR_OBSTRUCTION_PRESETS         157
#define IDD_ENTITY_PERSON               159
#define IDD_ENTITY_TRIGGER              161
#define IDR_IMAGEVIEW                   162
#define IDI_ENTITY_TRIGGER              164
#define IDI_ENTITY_PERSON               166
#define IDI_WINDOWSTYLE                 167
#define IDI_FONT                        169
#define IDR_SWATCHPALETTE               170
#define IDI_PV_GAME_SETTINGS            185
#define IDI_PV_CLOSED_FOLDER            186
#define IDI_PV_OPEN_FOLDER              187
#define IDI_IMAGETOOL_PENCIL            188
#define IDI_IMAGETOOL_LINE              189
#define IDI_IMAGETOOL_RECTANGLE         190
#define IDI_IMAGETOOL_CIRCLE            191
#define IDI_IMAGETOOL_FILL              192
#define IDI_MAPTOOL_1X1                 193
#define IDI_MAPTOOL_3X3                 194
#define IDI_MAPTOOL_5X5                 195
#define IDD_WINDOW_STYLE_PROPERTIES     196
#define IDI_MAPTOOL_COPYAREA            197
#define IDI_MAPTOOL_PASTE               198
#define IDI_MAPTOOL_SELECTTILE          199
#define IDI_MAPTOOL_FILLAREA            200
#define IDI_MAPTOOL_COPYENTITY          201
#define IDI_MAPTOOL_PASTEENTITY         202
#define IDR_SCRIPTVIEW                  203
#define IDI_MAPTOOL_OBS_SEGMENT         206
#define IDI_MAPTOOL_OBS_DELETE          207
#define IDI_LAYER_INVISIBLE             208
#define IDI_LAYER_VISIBLE               209
#define IDD_FONT_GRADIENT               210
#define IDD_TILE_OBSTRUCTION_DIALOG     211
#define IDD_STRING                      213
#define IDR_SPRITESET_IMAGES_PALETTE    214
#define IDD_ZONE_EDIT                   214
#define IDI_MAPTOOL_OBS_MOVE_PT         215
#define IDI_MAPTOOL_ZONEADD             216
#define IDI_MAPTOOL_ZONEEDIT            217
#define IDI_MAPTOOL_ZONEDELETE          218
#define IDI_IMAGETOOL_SELECTION         219
#define IDI_IMAGETOOL_ELLIPSE           221
#define IDD_DIALOG1                     222
#define IDD_DIALOG2                     223
#define IDC_PROJECTNAME                 1000
#define IDC_GAMETITLE                   1001
#define IDC_BROWSE                      1003
#define IDC_SCRIPT                      1008
#define IDC_NUMBER                      1011
#define IDC_NUMBERTEXT                  1012
#define IDC_WIDTH                       1013
#define IDC_HEIGHT                      1014
#define IDC_TILESET                     1015
#define IDC_NAME                        1018
#define IDC_ANIMATED                    1019
#define IDC_NEXT_TILE                   1020
#define IDC_DELAY                       1033
#define IDC_MUSIC                       1034
#define IDC_NEXT                        1035
#define IDC_PREVIOUS                    1036
#define IDC_SCREENWIDTH                 1044
#define IDC_SCREENHEIGHT                1045
#define IDC_TILESET_BROWSE              1048
#define IDC_SPRITESET                   1062
#define IDC_BROWSE_SPRITESET            1076
#define IDC_TILE_BACKGROUND             1081
#define IDC_STRETCH_BACKGROUND          1082
#define IDC_GRADIENT_BACKGROUND         1083
#define IDC_UPPER_LEFT                  1085
#define IDC_UPPER_RIGHT                 1086
#define IDC_TOP_COLOR                   1086
#define IDC_LOWER_LEFT                  1087
#define IDC_LOWER_RIGHT                 1088
#define IDC_HAS_PARALLAX                1089
#define IDC_VERTICAL_PARALLAX           1090
#define IDC_HORIZONTAL_PARALLAX         1091
#define IDC_HORIZONTAL_PARALLAX_VALUE   1092
#define IDC_VERTICAL_PARALLAX_VALUE     1093
#define IDC_PARALLAX_WARNING            1094
#define IDC_VERTICAL_SCROLLING          1095
#define IDC_HORIZONTAL_SCROLLING        1096
#define IDC_CHECK_SYNTAX                1096
#define IDC_HORIZONTAL_SCROLLING_VALUE  1097
#define IDC_VERTICAL_SCROLLING_VALUE    1098
#define IDC_ENTRY                       1101
#define IDC_EXIT                        1102
#define IDC_NORTH                       1103
#define IDC_EAST                        1104
#define IDC_SOUTH                       1105
#define IDC_WEST                        1106
#define IDC_SCRIPT_TYPE                 1110
#define IDC_REFLECTIVE                  1111
#define IDC_BOTTOM_COLOR                1112
#define IDC_EDIT_OBSTRUCTIONS           1113
#define IDC_PRESETS                     1114
#define IDC_VALUE                       1115
#define IDC_STEPS                       1116
#define IDC_AUTHOR                      1117
#define IDC_DESCRIPTION                 1118
#define ID_FILE_IMPORT_BITMAPTORSS      12241
#define ID_HELP_ABOUT                   40001
#define ID_FILE_EXIT                    40003
#define ID_FILE_CLOSEPROJECT            40009
#define ID_PROJECT_INSERT_MAP           40014
#define ID_HELP_SPHERESITE              40016
#define ID_HELP_FLIKSSITE               40017
#define ID_PROJECT_INSERT_SPRITESET     40018
#define ID_PROJECT_INSERT_SCRIPT        40020
#define ID_PROJECT_INSERT_IMAGE         40021
#define ID_PROJECT_INSERT_SOUND         40030
#define ID_FILE_NEW_PROJECT             40031
#define ID_FILE_NEW_MAP                 40032
#define ID_FILE_NEW_SPRITESET           40034
#define ID_FILE_NEW_SCRIPT              40035
#define ID_FILE_NEW_IMAGE               40036
#define ID_FILE_OPEN_PROJECT            40042
#define ID_FILE_OPEN_MAP                40043
#define ID_FILE_OPEN_SPRITESET          40045
#define ID_FILE_OPEN_SCRIPT             40046
#define ID_FILE_OPEN_IMAGE              40047
#define ID_FILE_OPEN_SOUND              40049
#define ID_PROJECTITEM_OPEN             40050
#define ID_PROJECTITEM_DELETE           40051
#define ID_SOUND_PLAY                   40052
#define ID_SOUND_STOP                   40053
#define ID_PROJECTGROUP_INSERT          40054
#define ID_FILE_SAVEAS                  40059
#define ID_FILE_SAVECOPYAS              40060
#define ID_PROJECT_RUNSPHERE            40066
#define ID_LAYERVIEW_INSERTLAYER        40086
#define ID_LAYERVIEW_PROPERTIES         40087
#define ID_LAYERVIEW_DELETELAYER        40088
#define ID_PROJECT_INSERT_ANIMATION     40092
#define ID_ANIMATION_PLAY               40093
#define ID_ANIMATION_STOP               40094
#define ID_MAPVIEW_SETENTRYPOINT        40096
#define ID_MAPVIEW_DELETEENTITY         40098
#define ID_MAPVIEW_EDITENTITY           40100
#define ID_FILE_IMPORT_IMAGETOMAPTILESET 40101
#define ID_MAP_PROPERTIES               40102
#define ID_PROJECT_INSERT_WINDOWSTYLE   40106
#define ID_PROJECT_INSERT_FONT          40107
#define ID_WINDOWSTYLE_RESIZESECTION    40109
#define ID_FONT_RESIZE                  40111
#define ID_FONT_SIMPLIFY                40114
#define ID_WINDOWSTYLE_ZOOM_1X          40115
#define ID_WINDOWSTYLE_ZOOM_2X          40116
#define ID_WINDOWSTYLE_ZOOM_4X          40117
#define ID_WINDOWSTYLE_ZOOM_8X          40118
#define ID_FILE_NEW_WINDOWSTYLE         40119
#define ID_FILE_NEW_FONT                40120
#define ID_FILE_OPEN_WINDOWSTYLE        40121
#define ID_FILE_OPEN_FONT               40122
#define ID_WINDOWSTYLE_EDIT_UPPERLEFT   40132
#define ID_WINDOWSTYLE_EDIT_TOP         40133
#define ID_WINDOWSTYLE_EDIT_UPPERRIGHT  40134
#define ID_WINDOWSTYLE_EDIT_RIGHT       40135
#define ID_WINDOWSTYLE_EDIT_LOWERRIGHT  40136
#define ID_WINDOWSTYLE_EDIT_BOTTOM      40137
#define ID_WINDOWSTYLE_EDIT_LOWERLEFT   40138
#define ID_WINDOWSTYLE_EDIT_LEFT        40139
#define ID_WINDOWSTYLE_EDIT_BACKGROUND  40140
#define ID_SPRITESET_FRAMEPROPERTIES    40150
#define ID_MAPVIEW_INSERTENTITY_PERSON  40154
#define ID_MAPVIEW_INSERTENTITY_TRIGGER 40155
#define ID_PROJECT_REFRESH              40159
#define ID_FILE_OPEN_ANIMATION          40162
#define ID_SPRITESETVIEWFRAMES_INSERT   40164
#define ID_SPRITESETVIEWFRAMES_DELETE   40165
#define ID_SPRITESETVIEWFRAMES_PROPERTIES 40166
#define ID_SPRITESETVIEWDIRECTIONS_INSERT 40167
#define ID_SPRITESETVIEWDIRECTIONS_DELETE 40168
#define ID_MAPVIEW_SELECTTILE           40170
#define ID_SPRITESETVIEWFRAMES_COPY     40176
#define ID_SPRITESETVIEWFRAMES_PASTE    40177
#define ID_SPRITESET_ZOOM_1X            40178
#define ID_SPRITESET_ZOOM_2X            40179
#define ID_SPRITESET_ZOOM_4X            40180
#define ID_SPRITESET_ZOOM_8X            40181
#define ID_MAP_CHANGETILESIZE           40183
#define ID_TILESETVIEW_INSERTTILE       40184
#define ID_TILESETVIEW_DELETETILE       40185
#define ID_TILESETVIEW_PROPERTIES       40186
#define ID_TILESETVIEW_INSERTTILES      40187
#define ID_TILESETVIEW_DELETETILES      40188
#define ID_OBSTRUCTIONPRESETS_UNBLOCKED 40189
#define ID_OBSTRUCTIONPRESETS_BLOCKED   40190
#define ID_OBSTRUCTIONPRESETS_UPPERRIGHT 40191
#define ID_OBSTRUCTIONPRESETS_LOWERRIGHT 40192
#define ID_OBSTRUCTIONPRESETS_LOWERLEFT 40193
#define ID_OBSTRUCTIONPRESETS_UPPERLEFT 40194
#define ID_SPRITESET_RESIZE             40195
#define ID_MAP_EXPORTTILESET            40196
#define ID_MAP_IMPORTTILESET            40197
#define ID_TILESETVIEW_APPENDTILE       40198
#define ID_TILESETVIEW_APPENDTILES      40199
#define ID_IMAGE_VIEWATORIGINALSIZE     40200
#define ID_SCRIPT_FIND                  40211
#define ID_SCRIPT_REPLACE               40212
#define ID_SPRITESETVIEWDIRECTIONS_APPEND 40213
#define ID_SPRITESETVIEWFRAMES_APPEND   40214
#define ID_MAPVIEW_ZOOM_1X              40215
#define ID_MAPVIEW_ZOOM_2X              40216
#define ID_MAPVIEW_ZOOM_4X              40218
#define ID_MAPVIEW_ZOOM_8X              40219
#define ID_PROJECT_CONFIGURESPHERE      40224
#define ID_SCRIPT_CHECKSYNTAX           40225
#define ID_PROJECT_PACKAGE_GAME         40226
#define ID_FILE_IMPORT_BITMAPTORTS      40227
#define ID_FILE_IMPORT_VERGEFONTTEMPLATE 40229
#define ID_IMAGEVIEW_COPY               40230
#define ID_IMAGEVIEW_PASTE              40231
#define ID_IMAGEVIEW_ROTATE_CW          40239
#define ID_IMAGEVIEW_ROTATE_CCW         40240
#define ID_IMAGEVIEW_SLIDE_UP           40241
#define ID_IMAGEVIEW_SLIDE_RIGHT        40242
#define ID_IMAGEVIEW_SLIDE_DOWN         40243
#define ID_IMAGEVIEW_SLIDE_LEFT         40244
#define ID_IMAGEVIEW_FLIP_HORIZONTALLY  40246
#define ID_IMAGEVIEW_FLIP_VERTICALLY    40247
#define ID_IMAGEVIEW_UNDO               40248
#define ID_IMAGEVIEW_FILL_RGB           40251
#define ID_IMAGEVIEW_FILL_ALPHA         40252
#define ID_IMAGEVIEW_FILL_BOTH          40253
#define ID_IMAGEVIEW_FILTER_BLUR        40254
#define ID_IMAGEVIEW_FILTER_NOISE       40255
#define ID_IMAGEVIEW_COLORPICKER        40256
#define ID_FILE_IMPORT_MERGE_RGBA       40257
#define ID_TILESETVIEW_INSERTTILESET    40258
#define ID_TILESETVIEW_APPENDTILESET    40259
#define ID_SWATCHPALETTE_DELETE         40458
#define ID_SWATCHPALETTE_INSERTBEFORE   40461
#define ID_SWATCHPALETTE_FILE_SAVE      40462
#define ID_SWATCHPALETTE_FILE_LOAD      40463
#define ID_SWATCHPALETTE_DEFAULT_DOS    40464
#define ID_SWATCHPALETTE_DEFAULT_VERGE  40465
#define ID_VIEW_PALETTES                40466
#define ID_SWATCHPALETTE_INSERTAFTER    40467
#define ID_FILE_IMPORT_WINDOWSFONT      40468
#define ID_FILE_OPENLASTPROJECT         40469
#define ID_IMAGE_RESIZE                 40470
#define ID_IMAGE_RESCALE                40472
#define ID_SWATCHPALETTE_REPLACE        40473
#define ID_LAYERVIEW_INSERTLAYERFROMIMAGE 40476
#define ID_FILE_SAVEALL                 40479
#define ID_WINDOW_CLOSEALL              40480
#define ID_WINDOWSTYLE_PROPERTIES       40481
#define ID_TILESETVIEW_ZOOM_1X          40482
#define ID_TILESETVIEW_ZOOM_2X          40483
#define ID_TILESETVIEW_ZOOM_4X          40484
#define ID_TILESETVIEW_ZOOM_8X          40485
#define ID_MAP_RESCALETILESET           40486
#define ID_MAP_PRUNETILESET             40487
#define ID_LAYERVIEW_DUPLICATELAYER     40489
#define ID_SCRIPTVIEW_UNDO              40490
#define ID_SCRIPTVIEW_CUT               40491
#define ID_SCRIPTVIEW_COPY              40492
#define ID_SCRIPTVIEW_PASTE             40493
#define ID_SCRIPTVIEW_DELETE            40494
#define ID_SCRIPTVIEW_SELECTALL         40495
#define ID_LAYERVIEW_EXPORTASIMAGE      40496
#define ID_MAPVIEW_FILL                 40498
#define ID_FILE_IMPORT_VERGEMAP         40499
#define ID_MAP_RESIZEALLLAYERS          40500
#define ID_IMAGEVIEW_SETCOLORALPHA      40501
#define ID_IMAGEVIEW_BLENDMODE_BLEND    40502
#define ID_IMAGEVIEW_BLENDMODE_REPLACE  40503
#define ID_IMAGEVIEW_BLENDMODE_RGBONLY  40504
#define ID_IMAGEVIEW_BLENDMODE_ALPHAONLY 40505
#define ID_FILE_IMPORT_VERGESPRITESET   40506
#define ID_IMAGEVIEW_SCALEALPHA         40507
#define ID_FONT_RESIZEALL               40508
#define ID_FONT_GENERATEGRADIENT        40510
#define ID_FILE_IMPORT_IMAGETOFONT      40511
#define ID_FONT_EXPORTTOIMAGE           40512
#define ID_SPRITESETVIEWDIRECTIONS_PROPERTIES 40513
#define ID_SPRITESETIMAGESPALETTE_MOVE_BACK 40514
#define ID_SPRITESETIMAGESPALETTE_MOVE_FORWARD 40515
#define ID_SPRITESETIMAGESPALETTE_INSERT_IMAGE 40516
#define ID_SPRITESETIMAGESPALETTE_REMOVE_IMAGE 40517
#define ID_SPRITESET_FILLDELAY          40518
#define ID_FONT_MAKECOLORTRANSPARENT    40519
#define ID_IMAGEVIEW_REPLACE_RGBA       40521
#define ID_IMAGEVIEW_REPLACE_RGB        40522
#define ID_IMAGEVIEW_REPLACE_ALPHA      40523
#define ID_MAPVIEW_ZONEEDIT             40524
#define ID_IMAGEVIEW_FILTER_SOLARIZE    40526
#define ID_SPRITESET_EXPORTASIMAGE      40527
#define ID_IMAGEVIEW_PASTE_ALPHA        40528
#define ID_IMAGEVIEW_PASTE_RGB          40529
#define ID_IMAGEVIEW_PASTE_INTO_SELECTION 40529
#define ID_IMAGEVIEW_VIEWGRID           40530
#define ID_IMAGEVIEW_FILTER_NEGATIVE_IMAGE_RGBA 40532
#define ID_IMAGEVIEW_FILTER_NEGATIVE_IMAGE_RGB 40533
#define ID_IMAGEVIEW_FILTER_NEGATIVE_IMAGE_ALPHA 40534
#define ID_MAP_TOGGLE_LOCK_LAYERS_IN_PLACE 40535
#define ID_LAYERVIEW_TOGGLE_LOCK_LAYERS_IN_PLACE 40535
#define ID_MAP_SLIDE_UP                 40536
#define ID_MAP_SLIDE_RIGHT              40537
#define ID_MAP_SLIDE_DOWN               40538
#define ID_MAP_SLIDE_LEFT               40539
#define ID_LAYERVIEW_SLIDE_RIGHT        40540
#define ID_LAYERVIEW_SLIDE_UP           40541
#define ID_LAYERVIEW_SLIDE_DOWN         40542
#define ID_LAYERVIEW_SLIDE_LEFT         40543
#define ID_TILESETVIEW_REPLACE_COLOR_WITH_COLOR 40544
#define ID_SCRIPT_OPTIONS_SET_FONT      40545
#define ID_SPRITESETVIEWFRAMES_REPLACE_COLOR_WITH_COLOR 40547
#define ID_SCRIPT_OPTIONS_TOGGLE_COLORS 40548
#define ID_LAYERVIEW_EXPORT_ALL_VISIBLE_LAYERS_AS_IMAGE 40549
#define ID_SCRIPT_OPTIONS_SET_TAB_SIZE  40550
#define ID_SCRIPT_OPTIONS_TOGGLE_LINE_NUMBERS 40551
#define ID_HELP_LOCALDOCUMENTATION      40552
#define ID_HELP_AEGISKNIGHTSSITE        40553
#define ID_HELP_SPHEREFAQ               40554
#define ID_IMAGE_RESAMPLE               40555
#define ID_IMAGEVIEW_SLIDE_OTHER        40556
#define ID_MAP_SLIDE_OTHER              40557
#define ID_LAYERVIEW_SLIDE_OTHER        40558
#define ID_IMAGEVIEW_FILTER_ADJUST_BRIGHTNESS 40561
#define ID_IMAGEVIEW_PASTE_INTOSELECTION 40563
#define ID_SPRITESETVIEWDIRECTIONS_EXPORT_AS_IMAGE 40564
#define ID_IMAGEVIEW_FILTER_ADJUST_GAMMA 40565
#define ID_SPRITESETVIEWDIRECTIONS_IMPORT_FROM_IMAGE 40567
#define ID_MAPVIEW_VIEWGRID             40569
#define ID_FILE_IMPORT_BITMAPTORWS      50505

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         40570
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
