import sys

Import('base_env BUILD_DIR COMPILER')

env = base_env.Copy()
COMPILER.SetupSphereCommon(env)
COMPILER.SetupAudiere(env)
COMPILER.SetupCorona(env)
COMPILER.SetupJS(env)
COMPILER.SetupMNG(env)
COMPILER.SetupWin32(env)
COMPILER.SetupZLib(env)

env.Prepend(
    RESPATH = [Dir('win32')],
    LIBPATH = ['win32'],
    LIBS = ['win32'])

if sys.platform == 'cygwin':
    env.Append(LIBS = ['winmm', 'wsock32'])
    md = 'win32'
else:
    md = 'unix'

engine = env.Program('engine', Split("""
    SpritesetServer.cpp
    benchmark.cpp
    engine.cpp
    log.cpp
    map_engine.cpp
    render.cpp
    rendersort.cpp
    script.cpp
    sfont.cpp
    simage.cpp
    smap.cpp
    sphere.cpp
    sspriteset.cpp
    swindowstyle.cpp
    engine.res
    """))

env.RES('engine.res', 'win32/engine.rc')
env.Install(BUILD_DIR, engine)

SConscript(dirs = [md])
