import sys
import autocons

Import('base_env BUILD_DIR COMPILER')

env = base_env.Copy()
COMPILER.SetupSphereCommon(env)
COMPILER.SetupAudiere(env)
COMPILER.SetupCorona(env)
COMPILER.SetupJS(env)
COMPILER.SetupMNG(env)
COMPILER.SetupWin32(env)
COMPILER.SetupZLib(env)
COMPILER.Win32Subsystem(env)
if COMPILER.needs_sdl():
    COMPILER.SetupSDL(env)

if COMPILER.is_win32():
	env.Prepend(
        RESPATH = [Dir('win32')],
        LIBPATH = ['win32'],
        LIBS = ['win32'])

if sys.platform == 'cygwin':
    env.Append(LIBS = ['winmm', 'wsock32'])
    md = 'win32'
else:
    md = 'unix'

engine_sources = Split("""
    SpritesetServer.cpp
    benchmark.cpp
    engine.cpp
    log.cpp
    map_engine.cpp
    render.cpp
    rendersort.cpp
    script.cpp
    sfont.cpp
    simage.cpp
    smap.cpp
    sphere.cpp
    sspriteset.cpp
    swindowstyle.cpp
    """)

if COMPILER.is_win32():
    engine_sources.append('engine.res')
    env.RES('engine.res', 'win32/engine.rc')

engine = env.Program('engine', engine_sources)
env.Install(BUILD_DIR, engine)

print "Using subsystem: ", md
SConscript(dirs = [md])
