import sys

Import('base_env SetupAudiere SetupCorona SetupJS SetupMNG SetupZLib')

env = base_env.Copy()

SetupAudiere(env)
SetupCorona(env)
SetupJS(env)
SetupMNG(env)
SetupZLib(env)

env.Prepend(
    LIBPATH = ['../common', 'win32'],
    LIBS = ['common', 'win32'])

if sys.platform == 'cygwin':
    env.Append(LIBS = ['winmm', 'wsock32'])
    md = 'win32'
else:
    md = 'unix'

engine = env.Program('engine', Split("""
    SpritesetServer.cpp
    benchmark.cpp
    engine.cpp
    log.cpp
    map_engine.cpp
    render.cpp
    rendersort.cpp
    script.cpp
    sfont.cpp
    simage.cpp
    smap.cpp
    sphere.cpp
    sspriteset.cpp
    swindowstyle.cpp
    """))

env.Install('#/build', engine)

SConscript(dirs = [md])
