Import('base_env')

base_env.Library('win32', Split("""
    win32_audio.cpp
    win32_filesystem.cpp
    win32_input.cpp
    win32_main.cpp
    win32_network.cpp
    win32_screenshot.cpp
    win32_sphere_config.cpp
    win32_time.cpp
    win32_video.cpp
    win32_wmain.cpp
    """))
