Import('base_env COMPILER')

env = base_env.Copy()
COMPILER.SetupAudiere(env)
COMPILER.SetupCorona(env)
COMPILER.SetupMNG(env)
COMPILER.SetupZLib(env)

env.Library('common', Split("""
    AnimationFactory.cpp
    DefaultFile.cpp
    DefaultFileSystem.cpp
    Entities.cpp
    FLICAnimation.cpp
    Filters.cpp
    Font.cpp
    Image32.cpp
    Layer.cpp
    Log.cpp
    LogDispatcher.cpp
    LogFile.cpp
    LogNull.cpp
    MNGAnimation.cpp
    Map.cpp
    ObstructionMap.cpp
    PackageFile.cpp
    PackageFileSystem.cpp
    Spriteset.cpp
    str_util.cpp
    Tile.cpp
    Tileset.cpp
    WindowStyle.cpp
    common_palettes.cpp
    configfile.cpp
"""))
