#ifndef IDS_HPP
#define IDS_HPP
#include <wx/wx.h>
#define wxID_base  (wxID_HIGHEST + 1000) //wxID_HIGHEST //wxEVT_USER_FIRST
enum wID_ {

  wEVT_TILESETVIEW_base = wxID_base + 100,

  wEVT_TILESETVIEW_INSERTTILE,
  wEVT_TILESETVIEW_APPENDTILE,
  wEVT_TILESETVIEW_DELETETILE,
  wEVT_TILESETVIEW_PROPERTIES,
  wEVT_TILESETVIEW_INSERTTILES,
  wEVT_TILESETVIEW_APPENDTILES,
  wEVT_TILESETVIEW_DELETETILES,
  wEVT_TILESETVIEW_INSERTTILESET,
  wEVT_TILESETVIEW_APPENDTILESET,

  wEVT_TILESETVIEW_ZOOM_,
  wEVT_TILESETVIEW_ZOOM_1X,
  wEVT_TILESETVIEW_ZOOM_2X,
  wEVT_TILESETVIEW_ZOOM_4X,
  wEVT_TILESETVIEW_ZOOM_8X,


  wID_TILEPROPERTIES_base = wxID_base + 200,

  wID_TILEPROPERTIES_ANIMATED,
  wID_TILEPROPERTIES_NEXT,
  wID_TILEPROPERTIES_PREVIOUS,
  wID_TILEPROPERTIES_EDIT_OBSTRUCTIONS,


  wID_TILEOBSTRUCTION_base = wxID_base + 300,

  wID_TILEOBSTRUCTION_PRESETS,
  wID_TILEOBSTRUCTION_PRESET_UNBLOCKED,
  wID_TILEOBSTRUCTION_PRESET_BLOCKED,
  wID_TILEOBSTRUCTION_PRESET_UPPER_LEFT,
  wID_TILEOBSTRUCTION_PRESET_UPPER_RIGHT,
  wID_TILEOBSTRUCTION_PRESET_LOWER_LEFT,
  wID_TILEOBSTRUCTION_PRESET_LOWER_RIGHT,


  wID_SWATCHPALETTE_base = wxID_base + 400,

  wID_SWATCHPALETTE_FILE_,
  wID_SWATCHPALETTE_FILE_LOAD,
  wID_SWATCHPALETTE_FILE_SAVE,
  wID_SWATCHPALETTE_DEFAULT_,
  wID_SWATCHPALETTE_DEFAULT_DOS,
  wID_SWATCHPALETTE_DEFAULT_VERGE,

  wID_SWATCHPALETTE_INSERTBEFORE,
  wID_SWATCHPALETTE_INSERTAFTER,
  wID_SWATCHPALETTE_REPLACE,
  wID_SWATCHPALETTE_DELETE,

  wID_TOOLPALETTE_base = wxID_base + 500,


  wID_SPRITESETIMAGESPALETTE_base = wxID_base + 600,

  wID_SPRITESETIMAGESPALETTE_MOVE_BACK,
  wID_SPRITESETIMAGESPALETTE_MOVE_FORWARD,
  wID_SPRITESETIMAGESPALETTE_INSERT_IMAGE,
  wID_SPRITESETIMAGESPALETTE_REMOVE_IMAGE,


  
  wID_TILESET_base = wxID_base + 700, 

  wID_TILESET_INSERTTILES, 
  wID_TILESET_APPENDTILES, 

  wID_TILESET_DELETETILE, 

  wID_TILESET_REPLACEWITHIMAGE, 
  wID_TILESET_INSERTIMAGE, 
  wID_TILESET_APPENDIMAGE, 



  wID_IMAGEVIEW_base = wxID_base + 800,

  wID_IMAGEVIEW_COLORPICKER,
  wID_IMAGEVIEW_UNDO,
  wID_IMAGEVIEW_COPY,
  wID_IMAGEVIEW_PASTE,
  wID_IMAGEVIEW_BLENDMODE_,
  wID_IMAGEVIEW_BLENDMODE_BLEND,
  wID_IMAGEVIEW_BLENDMODE_REPLACE,
  wID_IMAGEVIEW_BLENDMODE_RGBONLY,
  wID_IMAGEVIEW_BLENDMODE_ALPHAONLY,
  wID_IMAGEVIEW_ROTATE_,
  wID_IMAGEVIEW_ROTATE_CW,
  wID_IMAGEVIEW_ROTATE_CCW,
  wID_IMAGEVIEW_SLIDE_,
  wID_IMAGEVIEW_SLIDE_UP,
  wID_IMAGEVIEW_SLIDE_RIGHT,
  wID_IMAGEVIEW_SLIDE_DOWN,
  wID_IMAGEVIEW_SLIDE_LEFT,
  wID_IMAGEVIEW_FLIP_,
  wID_IMAGEVIEW_FLIP_HORIZONTALLY,
  wID_IMAGEVIEW_FLIP_VERTICALLY,
  wID_IMAGEVIEW_FILL_,
  wID_IMAGEVIEW_FILL_RGB,
  wID_IMAGEVIEW_FILL_ALPHA,
  wID_IMAGEVIEW_FILL_BOTH,
  wID_IMAGEVIEW_REPLACE_,
  wID_IMAGEVIEW_REPLACE_RGBA,
  wID_IMAGEVIEW_REPLACE_RGB,
  wID_IMAGEVIEW_REPLACE_ALPHA,
  wID_IMAGEVIEW_FILTER_,
  wID_IMAGEVIEW_FILTER_BLUR,
  wID_IMAGEVIEW_FILTER_NOISE,
  wID_IMAGEVIEW_SETCOLORALPHA,
  wID_IMAGEVIEW_SCALEALPHA,


  wID_SPRITESETVIEW_base = wxID_base + 900,

  wID_SPRITESETVIEWDIRECTIONS_INSERT, 
  wID_SPRITESETVIEWDIRECTIONS_DELETE, 
  wID_SPRITESETVIEWDIRECTIONS_APPEND, 
  wID_SPRITESETVIEWDIRECTIONS_PROPERTIES, 

  wID_SPRITESETVIEWFRAMES_INSERT, 
  wID_SPRITESETVIEWFRAMES_DELETE, 
  wID_SPRITESETVIEWFRAMES_APPEND, 
  wID_SPRITESETVIEWFRAMES_COPY, 
  wID_SPRITESETVIEWFRAMES_PASTE, 
  wID_SPRITESETVIEWFRAMES_PROPERTIES, 


  wID_LAYERVIEW_base = wxID_base + 1000,

  wID_LAYERVIEW_INSERTLAYER,
  wID_LAYERVIEW_INSERTLAYERFROMIMAGE,
  wID_LAYERVIEW_DELETELAYER,
  wID_LAYERVIEW_DUPLICATELAYER,
  wID_LAYERVIEW_PROPERTIES,
  wID_LAYERVIEW_EXPORTASIMAGE,


  wID_MAPVIEW_base = wxID_base + 1100,

  wID_MAPVIEW_SELECTTILE,
  wID_MAPVIEW_SETENTRYPOINT,
  wID_MAPVIEW_FILL,
  wID_MAPVIEW_INSERTENTITY_,
  wID_MAPVIEW_INSERTENTITY_PERSON,
  wID_MAPVIEW_INSERTENTITY_TRIGGER,
  wID_MAPVIEW_DELETEENTITY,
  wID_MAPVIEW_EDITENTITY,
  wID_MAPVIEW_ZONEEDIT,
  wID_MAPVIEW_ZOOM_,
  wID_MAPVIEW_ZOOM_1X,
  wID_MAPVIEW_ZOOM_2X,
  wID_MAPVIEW_ZOOM_4X,
  wID_MAPVIEW_ZOOM_8X,

  
  wID_TRIGGERDIALOG_base = wxID_base + 1200,

  wID_TRIGGERDIALOG_CHECK_SYNTAX,
  wID_TRIGGERDIALOG_SCRIPT,


  wID_FILE_base = wxID_base + 1300,

  wID_FILE_CLOSE,

  wID_FILE_SAVE,
  wID_FILE_SAVEAS,
  wID_FILE_SAVECOPYAS,


  wID_IMAGE_base = wxID_base + 1400,

  wID_IMAGE_RESIZE,
  wID_IMAGE_RESCALE,
  wID_IMAGE_VIEWORIGINALSIZE,


  wID_SOUND_base = wxID_base + 1500,

  wID_SOUND_PLAY,
  wID_SOUND_STOP,
  wID_SOUND_TIMER,


  wID_SCRIPT_base = wxID_base + 1600,

  wID_SCRIPT_ID,

  wID_SCRIPT_CHECKSYNTAX,
  wID_SCRIPT_FIND,
  wID_SCRIPT_REPLACE,


  wID_ANIMATION_base = wxID_base + 1700,

  wID_ANIMATION_TIMER,


  wID_FONT_base = wxID_base + 1800,

  wID_FONT_SCROLL,

  wID_FONT_RESIZE,
  wID_FONT_RESIZEALL,
  wID_FONT_SIMPLIFY,
  wID_FONT_MAKECOLORTRANSPARENT,
  wID_FONT_GENERATEGRADIENT,


  wID_MAP_base = wxID_base + 1900,

  wID_MAP_TAB, // the tab id
  wID_MAP_TAB_, // the tab menu id
  wID_MAP_TAB_MAP,
  wID_MAP_TAB_TILES,

  wID_MAP_PROPERTIES,
  wID_MAP_CHANGETILESIZE,
  wID_MAP_RESCALETILESET,
  wID_MAP_RESAMPLETILESET,
  wID_MAP_RESIZEALLLAYERS,
  wID_MAP_EXPORTTILESET,
  wID_MAP_IMPORTTILESET,
  wID_MAP_PRUNETILESET,

  wID_SPRITESET_base = wxID_base + 2000,

  wID_SPRITESET_TAB, // the tab control
  wID_SPRITESET_TAB_, // the tab menu id
  wID_SPRITESET_TAB_FRAMES,
  wID_SPRITESET_TAB_EDIT,
  wID_SPRITESET_TAB_BASE,

  wID_SPRITESET_ZOOM_,
  wID_SPRITESET_ZOOM_1X,
  wID_SPRITESET_ZOOM_2X,
  wID_SPRITESET_ZOOM_4X,
  wID_SPRITESET_ZOOM_8X,
  wID_SPRITESET_RESIZE,
  wID_SPRITESET_FILLDELAY,
  wID_SPRITESET_FRAMEPROPERTIES,


  wID_WINDOWSTYLE_base = wxID_base + 2100,

  wID_WINDOWSTYLE_EDIT_UPPERLEFT,
  wID_WINDOWSTYLE_EDIT_TOP,
  wID_WINDOWSTYLE_EDIT_UPPERRIGHT,
  wID_WINDOWSTYLE_EDIT_RIGHT,
  wID_WINDOWSTYLE_EDIT_LOWERRIGHT,
  wID_WINDOWSTYLE_EDIT_BOTTOM,
  wID_WINDOWSTYLE_EDIT_LOWERLEFT,
  wID_WINDOWSTYLE_EDIT_LEFT,
  wID_WINDOWSTYLE_EDIT_BACKGROUND,

  wID_WINDOWSTYLE_RESIZESECTION,

  wID_WINDOWSTYLE_ZOOM_1X,
  wID_WINDOWSTYLE_ZOOM_2X,
  wID_WINDOWSTYLE_ZOOM_4X,
  wID_WINDOWSTYLE_ZOOM_8X,

  wID_WINDOWSTYLE_PROPERTIES,


  wID_TILESETDIALOG_base = wxID_base + 2200,

  wID_TILESETDIALOG_BROWSE,


  wID_ZONEEDITDIALOG_base = wxID_base + 2300,

  wID_ZONEEDITDIALOG_CHECK_SYNTAX,
  wID_ZONEEDITDIALOG_SCRIPT,


  wID_TILESETSELECTIONDIALOG_base = wxID_base + 2400,

  wID_TILESETSELECTIONDIALOG_BROWSE,


  wID_MAPPROPERTIESDIALOG_base = wxID_base + 2500,
  
  wID_MAPPROPERTIESDIALOG_CHECK_SYNTAX,
  wID_MAPPROPERTIESDIALOG_RADIOBOX,


  wID_ENTITYPERSONDIALOG_base = wxID_base + 2600,

  wID_ENTITYPERSONDIALOG_BROWSE_SPRITESET,
  wID_ENTITYPERSONDIALOG_CHECK_SYNTAX,
  wID_ENTITYPERSONDIALOG_RADIOBOX,


  wID_LAYERPROPERTIESDIALOG_base = wxID_base + 2700,

  wID_LAYERPROPERTIESDIALOG_HAS_PARALAX,


  wID_PROJECTWINDOWS_base = wxID_base + 2800,

  wID_PROJECTWINDOWS_TREE,


  wID_MAIN_base = wxID_base + 2900,

  // generic file open
  wID_FILE_OPEN,

  // project
  wID_FILE_NEW_PROJECT,
  wID_FILE_OPEN_PROJECT,
  wID_FILE_CLOSEPROJECT,
  wID_FILE_OPENLASTPROJECT,

  // file | new
  wID_FILE_NEW_,

  wID_FILE_NEW_MAP,
  wID_FILE_NEW_SPRITESET,
  wID_FILE_NEW_SCRIPT,
  wID_FILE_NEW_FONT,
  wID_FILE_NEW_WINDOWSTYLE,
  wID_FILE_NEW_IMAGE,

  // file | open
  wID_FILE_OPEN_,
  wID_FILE_OPEN_MAP,
  wID_FILE_OPEN_SPRITESET,
  wID_FILE_OPEN_SCRIPT,
  wID_FILE_OPEN_SOUND,
  wID_FILE_OPEN_FONT,
  wID_FILE_OPEN_WINDOWSTYLE,
  wID_FILE_OPEN_IMAGE,
  wID_FILE_OPEN_ANIMATION,

  // file | import
  wID_FILE_IMPORT_,
  wID_FILE_IMPORT_IMAGETOMAPTILESET,
  wID_FILE_IMPORT_BITMAPTORWS,
  wID_FILE_IMPORT_BITMAPTORSS,
  wID_FILE_IMPORT_BITMAPTORTS,
  wID_FILE_IMPORT_VERGEFONTTEMPLATE,
  wID_FILE_IMPORT_VERGEMAP,
  wID_FILE_IMPORT_VERGESPRITESET,
  wID_FILE_IMPORT_MERGE_RGBA,
  wID_FILE_IMPORT_WINDOWSFONT,

  wID_FILE_SAVEALL,

  wID_FILE_OPTIONS,
  wID_FILE_EXIT,

  // insert
  wID_PROJECT_INSERT_MAP,
  wID_PROJECT_INSERT_SPRITESET,
  wID_PROJECT_INSERT_SCRIPT,
  wID_PROJECT_INSERT_SOUND,
  wID_PROJECT_INSERT_FONT,
  wID_PROJECT_INSERT_WINDOWSTYLE,
  wID_PROJECT_INSERT_IMAGE,
  wID_PROJECT_INSERT_ANIMATION,

  wID_PROJECT_REFRESH,
  wID_PROJECT_RUNSPHERE,
  wID_PROJECT_CONFIGURESPHERE,
  wID_PROJECT_PACKAGE_GAME,

  wID_WINDOW_CLOSEALL,

  wID_HELP_CONTENTS,
  wID_HELP_ABOUT,


  wID_SCROLL_base = wxID_base + 3000,

  wID_SCROLL_HORIZONTAL,
  wID_SCROLL_VERTICAL,

};



#endif //IDS_HPP
