Import('base_env')

env = base_env.Copy()

env.Append(RESPATH = [Dir('.')],
           LIBPATH = [Dir('../common')],
           LIBS = ['common', 'comctl32'])

# we need win32_sphere_config.cpp in our current directory, because SCons won't let us try to build it twice  :(
config = env.Object('win32_sphere_config',
                    '../engine/win32/win32_sphere_config.cpp')
node = env.Program('config', [
    'main.cpp',
    config,
    'config.res'])
env.Resource('config.res', 'config.rc')
env.Install("#/build", node)
