Import('base_env BUILD_DIR COMPILER')

env = base_env.Copy()
COMPILER.SetupSphereCommon(env)
COMPILER.SetupWin32(env)

env.Append(RESPATH = [Dir('.')])

# we need win32_sphere_config.cpp in our current directory, because SCons won't let us try to build it twice  :(
config = env.Object('win32_sphere_config',
                    '../engine/win32/win32_sphere_config.cpp')
node = env.Program('config', [
    'main.cpp',
    config,
    'config.res'])
env.RES('config.res', 'config.rc')
env.Install(BUILD_DIR, node)
