Import('base_env')

env = base_env.Copy()
env.Append(
    LIBPATH = Dir('../common'),
    LIBS = ['vidcommon', 'ddraw', 'gdi32'],
    RESPATH = Dir('../common'))

drv = env.SharedLibrary(
    'standard32',
    ['standard32.cpp', 'standard.res', '../common/video.def'])
env.Resource('standard.res', 'standard.rc')

env.Install('#/build/system/video', drv)
